Repository Leiner117/Pedidos-Express, pull requests merged in 2025-05, with the labels that each got.

#36 feat: Add scripts to populate meals, orders, and restaurants; implement startup event for database initialization
  backend/app.py
  backend/db/__init__.py
  backend/scripts/populate_meals.py
  backend/scripts/populate_orders.py
  backend/scripts/populate_restaurants.py
Labels: enhancement

#37 feat: Add restaurant routes and schemas for detailed restaurant information
  backend/routes/__init__.py
  backend/routes/restaurants.py
  backend/schemas/restaurant.py
Labels: enhancement

#41 feat: Add endpoint to retrieve meals by restaurant ID with error handling
  backend/routes/restaurants.py
Labels: enhancement, backend

#42 feat: add addRestaurant page
  frontend/pages/addRestaurant/addRestaurant.html
  frontend/pages/addRestaurant/scripts/addRestaurant.js
Labels: In progress
